env:
  PLUGIN_VERIFIER_IDE_VERSIONS: 2023.2.6 2023.3.6 2024.1
jobs:
  gradleValidation:
    name: Gradle Wrappers
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Fetch Sources
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/actions/wrapper-validation@v3.3.1
  mirror:
    if: github.ref == 'refs/heads/main' && github.repository == 'JetBrains/intellij-sdk-docs'
    name: Code Samples Mirror
    needs: samples
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - continue-on-error: true
      name: Prepare Mirror
      run: 'git clone --bare git@github.com:JetBrains/intellij-sdk-docs.git .

        git branch | grep -v "main" | xargs -r git branch -D

        git filter-branch --prune-empty --subdirectory-filter code_samples main

        git push --mirror git@github.com:JetBrains/intellij-sdk-code-samples.git

        '
  samples:
    name: Code Samples / ${{ matrix.plugin }}
    needs: gradleValidation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Fetch Sources
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Verify Plugin
      run: (cd code_samples/${{ matrix.plugin }}; ./gradlew verifyPlugin)
    - continue-on-error: true
      name: Test Plugin
      run: (cd code_samples/${{ matrix.plugin }}; ./gradlew test)
    - continue-on-error: true
      id: properties
      name: Export Properties
      run: 'echo "ideVersions=${PLUGIN_VERIFIER_IDE_VERSIONS// /-}" >> $GITHUB_OUTPUT

        echo "pluginVerifierHomeDir=~/.pluginVerifier" >> $GITHUB_OUTPUT

        '
      shell: bash
    - continue-on-error: true
      name: Run Plugin Verifier
      run: "echo \"\ntasks {\n  runPluginVerifier {\n    ideVersions.set(\"\\\"$PLUGIN_VERIFIER_IDE_VERSIONS\\\
        \"\".split(' ').toList())\n  }\n}\n\" >> code_samples/${{ matrix.plugin }}/build.gradle.kts\n\
        cd code_samples/${{ matrix.plugin }}\n./gradlew runPluginVerifier -Pplugin.verifier.home.dir=${{\
        \ steps.properties.outputs.pluginVerifierHomeDir }}\n"
    - continue-on-error: true
      if: ${{ always() }}
      name: Collect Plugin Verifier Result
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.plugin }}-pluginVerifier-result
        path: ${{ github.workspace }}/code_samples/${{ matrix.plugin }}/build/reports/pluginVerifier
    strategy:
      fail-fast: false
      matrix:
        plugin:
        - action_basics
        - comparing_string_references_inspection
        - conditional_operator_intention
        - editor_basics
        - facet_basics
        - framework_basics
        - kotlin_demo
        - live_templates
        - max_opened_projects
        - module
        - project_model
        - project_view_pane
        - project_wizard
        - psi_demo
        - run_configuration
        - simple_language_plugin
        - tool_window
        - tree_structure_provider
name: Code Samples
on:
  repository_dispatch:
    types: trigger-ga___code-samples.yml
