jobs:
  combine-prs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: fetch-branch-names
      name: Fetch branch names
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: "const MUST_BE_GREEN = '${{ github.event.inputs.mustBeGreen }}' ===\
          \ 'true';\nconst BRANCH_PREFIX = '${{ github.event.inputs.branchPrefix }}';\n\
          const IGNORE_LABEL = '${{ github.event.inputs.ignoreLabel }}';\n\nconst\
          \ pulls = await github.paginate('GET /repos/:owner/:repo/pulls', {\n  owner:\
          \ context.repo.owner,\n  repo: context.repo.repo\n});\n\nconst branches\
          \ = [];\nconst prs = [];\nlet base_branch = null;\n\nawait Promise.all(pulls.map(async\
          \ pull => {\n  const branch = pull['head']['ref'];\n  console.log('Pull\
          \ for branch: ' + branch);\n  if (branch.startsWith(BRANCH_PREFIX)) {\n\
          \    console.log('Branch matched: ' + branch);\n\n    if (MUST_BE_GREEN)\
          \ {\n      console.log('Checking green status: ' + branch);\n      const\
          \ checkSuites = await github.paginate('GET /repos/:owner/:repo/commits/:commit/check-suites',\
          \ {\n        owner: context.repo.owner,\n        repo: context.repo.repo,\n\
          \        commit: pull['head']['sha']\n      });\n      const success = checkSuites.every(suite\
          \ => suite['conclusion'] === 'success' || suite['conclusion'] === null)\n\
          \      if (!success) {\n        return;\n      }\n    }\n    console.log('Checking\
          \ labels: ' + branch);\n    const labels = pull['labels'];\n    for (const\
          \ label of labels) {\n      const labelName = label['name'];\n      console.log('Checking\
          \ label: ' + labelName);\n      if (labelName === IGNORE_LABEL) {\n    \
          \    console.log('Discarding ' + branch + ' with label ' + labelName);\n\
          \          return;\n      }\n    }\n\n    console.log('Adding branch to\
          \ array: ' + branch);\n\n    branches.push(branch);\n    prs.push('#' +\
          \ pull['number'] + ' ' + pull['title']);\n    base_branch = pull['base']['ref'];\n\
          \  }\n}))\n\nif (branches.length === 0) {\n  core.setFailed('No PRs/branches\
          \ matched criteria');\n  return;\n}\n\ncore.setOutput('base-branch', base_branch);\n\
          core.setOutput('prs-string', prs.join('\\n'));\n\ncombined = branches.join('\
          \ ')\nconsole.log('Combined: ' + combined);\nreturn combined\n"
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      env:
        BASE_BRANCH: ${{ steps.fetch-branch-names.outputs.base-branch }}
        BRANCHES_TO_COMBINE: ${{ steps.fetch-branch-names.outputs.result }}
        COMBINE_BRANCH_NAME: ${{ github.event.inputs.combineBranchName }}
      name: Created combined branch
      run: 'echo "$BRANCHES_TO_COMBINE"

        sourcebranches="${BRANCHES_TO_COMBINE%\"}"

        sourcebranches="${sourcebranches#\"}"


        basebranch="${BASE_BRANCH%\"}"

        basebranch="${basebranch#\"}"


        git config pull.rebase false

        git config user.name github-actions

        git config user.email github-actions@github.com


        git branch $COMBINE_BRANCH_NAME $basebranch

        git checkout $COMBINE_BRANCH_NAME

        git pull origin $sourcebranches --no-edit

        git push origin $COMBINE_BRANCH_NAME

        '
    - continue-on-error: true
      env:
        PRS_STRING: ${{ steps.fetch-branch-names.outputs.prs-string }}
      name: Create Combined Pull Request
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: "const prString = process.env.PRS_STRING;\nconst body = 'This PR was\
          \ created by the Combine PRs action by combining the following PRs:\\n'\
          \ + prString;\nawait github.pulls.create({\n  owner: context.repo.owner,\n\
          \  repo: context.repo.repo,\n  title: '\U0001F6E0 Dependabot Combined PR',\n\
          \  head: '${{ github.event.inputs.combineBranchName }}',\n  base: '${{ steps.fetch-branch-names.outputs.base-branch\
          \ }}',\n  body: body\n});\n"
name: Dependabot Combine PRs
on:
  repository_dispatch:
    types: trigger-ga___dependabot-combine-prs.yml
