jobs:
  generate:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Generate
      run: ${GITHUB_WORKSPACE}/.github/scripts/libraries_releases.main.kts
    - continue-on-error: true
      name: Commit changes
      uses: Endbug/add-and-commit@v9
      with:
        add: v-releases.list
        message: Generate Libraries releases variable file
name: Generate Libraries releases variable file
on:
  repository_dispatch:
    types: trigger-ga___generate-libraries-releases.yml
