jobs:
  documentedProblemsPageVerification:
    name: Documented Problems Page Verification
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Fetch Sources
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Download Plugin Verifier
      run: "curl -s https://api.github.com/repos/JetBrains/intellij-plugin-verifier/releases/latest\
        \ \\\n  | jq -r '.assets[].browser_download_url' \\\n  | xargs curl -L --output\
        \ ~/verifier-all.jar\n"
    - continue-on-error: true
      name: Run Plugin Verifier
      run: 'PR_REPOSITORY=$(jq -re ".pull_request.head.repo.full_name // empty" $GITHUB_EVENT_PATH)
        || true

        REPOSITORY=${PR_REPOSITORY:-$GITHUB_REPOSITORY}

        REF=${GITHUB_HEAD_REF:-${GITHUB_REF#*/*/}}

        java -cp ~/verifier-all.jar com.jetbrains.pluginverifier.filtering.documented.DocumentedProblemsPageVerifierMain
        $REPOSITORY $REF

        '
name: Check API Changes pages
on:
  repository_dispatch:
    types: trigger-ga___verify-api-changes-pages.yml
